dist: trusty 
language: node_js
node_js:
  - stable
services:
  - mongodb
before_script:
  - sleep 10
  - mongo cookbookTest --eval 'db.createUser({user:"cookbook",pwd:"12345678",roles:["readWrite"]});'
notifications:
  email:
    recipients:
      - markus.kral@googlemail.com
    on_success: never       
    on_failure: always       
script:
  - npm run coverage
  - npm run check-coverage
after_success:
  - npm run report-coverage
after_failure:
  - npm run report-coverage
install:            
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - npm install
before_script:      # NEW
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
